# Generated by Django 5.0.2 on 2024-03-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='video_url',
        ),
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.CharField(default='Aayushmaan', max_length=100),
            preserve_default=False,
        ),
    ]
