# Generated by Django 5.0.2 on 2024-03-02 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_remove_course_video_url_course_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='author',
        ),
    ]
