# Generated by Django 5.0.2 on 2024-03-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_remove_course_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.CharField(default='Aayushmaan', max_length=100),
        ),
    ]
